[profile.default]
src = "src"
out = "out"
script = 'script'
libs = ["lib"]
solc = '0.8.16'
# Disabling optimizations to keep the current behavior
optimizer = false

fs_permissions = [
    { access = "read", path = "./out/" },
    { access = "read", path = "./script/input/" },
    { access = "read-write", path = "./script/output/" }
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
